<?php
return [
    'site-name'          => 'OtterNova System',
    'copyrights'         => 'Copyrights &copy; 2025-{0} <b>OtterNova</b> All rights reserved.',
    'change-language'    => 'Change Language',
    'go-to-main-site'    => 'Go to main site',
    'system-generated'   => 'This field is generated by the system.',
    'pages'              => [
        'login'              => 'Login',
        'create-account'     => 'Create an Account',
        'forgot-password'    => 'Forgot Password',
        'reset-password'     => 'Reset Password',
        'account-activation' => 'Account Activation',
    ],
    'response-msg'       => [
        'error'   => [
            'generic'                   => 'Sorry, something went wrong. Please try again later.',
            'please-check-empty-field'  => 'Please check required field.',
            'password-does-not-matched' => 'Sorry, the confirm password does not match.',
            'password-failed'           => 'Sorry, failed to update your password.',
            'wrong-credentials'         => 'Your username or password is incorrect, please try again.',
            'inactive-account'          => 'Your account is not active. Please contact your administrator or email the support team.',
            'not-logged-in'             => 'Please login to continue.',
            'session-expired'           => 'Your session has expired. Please login to continue.',
            'business-inactive'         => 'You cannot switch to this business.',
            'db-issue'                  => 'Your data could not be saved at the moment. Please try again later.',
            'upload-failed'             => 'Sorry, the file failed to be uploaded.',
            'removed'                   => 'Sorry, the file failed to be removed.',
            'no-permission'             => 'You do not have permission to access this feature.',
            'account-created-issue'     => 'Sorry, there was an error creating your account.',
        ],
        'success' => [
            'business-switched'     => 'You have successfully switched your business.',
            'data-saved'            => 'Your data has been saved.',
            'data-deleted'          => 'Your data has been deleted.',
            'password-changed'      => 'Your password has been changed.',
            'uploaded'              => 'Your file has been uploaded.',
            'removed'               => 'Your file has been removed.',
            'contract-renewal-done' => 'Your contract renewal has been recorded, please make a payment',
            'account-created'       => 'Your account has been created. Please check your email and activate your account before logging in.',
        ]
    ],
    'buttons'            => [
        'new'             => '<i class="fa-solid fa-circle-plus"></i> New',
        'edit'            => '<i class="fa-solid fa-pen-to-square"></i> Edit',
        'save'            => '<i class="fa-solid fa-floppy-disk"></i> Save',
        'upload'          => '<i class="fa-solid fa-cloud-arrow-up"></i> Upload',
        'remove'          => '<i class="fa-solid fa-trash-can"></i> Remove',
        'remove-confirm'  => '<i class="fa-solid fa-triangle-exclamation"></i> Remove Confirmation',
        'switch-role'     => 'Switch Role',
        'switch-business' => 'Switch Business',
        'filter'          => '<i class="fa-solid fa-filter"></i> Filter',
        'reset'           => 'Reset',
        'view-more'       => '<i class="fa-regular fa-eye"></i> View More',
    ],
    'generic-term'       => [
        'no-data' => 'No data'
    ],
    'generic-field'      => [
        'created_by' => 'Created By',
        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
    ],
    'login'              => [
        'title'             => 'Login',
        'instruction'       => 'Please login to your account.',
        'fields'            => [
            'username'             => 'Username (email address)',
            'username-empty-error' => 'Please enter your username (email address).',
            'password'             => 'Password',
            'password-empty-error' => 'Please enter your password.',
        ],
        'dont-have-account' => 'Don’t have an account?',
    ],
    'create-account'     => [
        'instruction'          => 'Enter your personal details to create account',
        'fields'               => [
            'full-name'             => 'Full name',
            'full-name-empty-error' => 'Please enter your full name.',
            'first-name'            => 'First name',
            'last-name'             => 'Last name',
            'username'              => 'Username (email address)',
            'username-empty-error'  => 'Please enter your username (email address).',
            'password'              => 'Password',
            'password-empty-error'  => 'Please enter your password.',
            'confirm-password'      => 'Confirm password',
            'business-name'         => 'Your business name',
            'country-code'          => 'Country',
            'country-code-note'     => 'You cannot change your country after your account is created.',
            'plan'                  => 'Select your plan',
            'plan-empty-error'      => 'Please select your plan.',
            'plan-options'          => [
                'basic'    => 'Basic',
                'standard' => 'Standard',
                'premium'  => 'Premium',
            ],
            'i-agree'               => 'I agree to the ',
            'terms'                 => 'Terms & Conditions',
            'terms-error'           => 'You must agree before creating your account.'
        ],
        'already-have-account' => 'Already have an account?',
    ],
    'forgot-password'    => [
        'instruction'    => 'Please enter your email address and follow the instructions on how to reset your password.',
        'email-address'  => 'Email address',
        'submit'         => 'Reset Password',
        'submit-success' => 'Your reset password request has been received. Please check your email and click the link to reset your password within 5 minutes.',
        'submit-error'   => 'An error has occurred, please try again later.'
    ],
    'reset-password'     => [
        'instruction'     => 'Please enter your new password',
        'fields'          => [
            'password'                     => 'New Password',
            'password-confirm'             => 'Confirm Password',
            'password-empty-error'         => 'Please enter your password.',
            'password-confirm-empty-error' => 'Please enter your confirm password.',
        ],
        'change-password' => 'Change Password',
        'token-invalid'   => 'Your token is invalid or expired, please start over again.'
    ],
    'account-activation' => [
        'success-message' => 'You account has been activated, you may proceed to login.',
        'error-message'   => 'Sorry, something went wrong. Please contact OtterNova support team.',
        'errors'          => [
            'bad-token'  => 'Your token is invalid. [TKN]',
            'expired'    => 'Your token is expired.',
            'not-found'  => 'Your token is invalid. [UID]',
            'wrong-hash' => 'Your token is invalid. [EML]'
        ]
    ],
    'email'              => [
        'footer-line'        => 'This email is autogenerated.',
        'footer-privacy'     => 'Privacy Policy',
        'footer-terms'       => 'Terms & Conditions',
        'account-activation' => [
            'subject' => 'OtterNova Account Activation',
            'message' => 'Welcome to OtterNova! We are so delighted to serve you.<br><br>To continue setting up, please activate your OtterNova account by clicking: <a href="{0}" target="_blank">here</a> or use the following link:<br><br>{1}',
        ],
        'new-user'           => [
            'subject' => 'Welcome to OtterNova - Your account has been created.',
            'message' => 'Welcome! Your OtterNova account has been created, and you can activate your account by clicking the link below, then, login using the following username and password.<br><br>Activation Link: <a href="{0}" target="_blank">{0}</a><br><br>Username: <b>{1}</b><br><br>Password: <b>{2}</b>',
        ]
    ]
];
